name: Test

on:
  push:
    branches:
      - feature/**

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install java 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Maven 3.8.4
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4
      - name: Test backend
        working-directory: ./backend
        run: mvn clean test
